- platform: group
  name: Dollhouse Roos
  unique_id: roos_dollhouse_homekit
  entities:
    - light.dollhouseroos_segment_1
    - light.dollhouseroos_segment_2
    - light.dollhouseroos_segment_3
    - light.dollhouseroos_segment_4
- platform: group
  name: Dollhouse Fran
  unique_id: fran_dollhouse_homekit
  entities:
    - light.dollhousefran_segment_1
    - light.dollhousefran_segment_2
    - light.dollhousefran_segment_3
    - light.dollhousefran_segment_4
