- id: nighty-night
  alias: Turn off the lights at 00:15
  description: ''
  trigger:
  - at: 00:15
    platform: time
  condition: []
  action:
    - service: script.turn_on
      entity_id: script.turn_off_downstairs

- id: evening-mode
  alias: Turn on lights at 20:00
  description: ''
  trigger:
  - at: '20:00'
    platform: time
  condition: []
  action:
    - service: script.turn_on
      entity_id: script.turn_on_downstairs
    - service: light.turn_on

- id: light-submarine
  alias: 'Make the hallway use red light at night'
  trigger:
    - platform: time
      at: 19:00
  action:
    - service: light.turn_on
      entity_id: light.badkamer
      brightess: 35
      transition: 2
      color_name: red

- id: presence-leave
  alias: 'Turn off things when leaving'
  trigger:
    - platform: state
      entity_id: person.piet_jaspers
      to: 'not_home'
  action:
    - service: notify.mobile_app_proteus
      data:
        title: "You not here"
        message: "You left"

- id: wake-girls
  alias: "Turn on the lights for the girls"
  trigger:
    - platform: time
      at: '07:00'
  action:
    - service: homeassistant.turn_on
      entity_id:
        - switch.fran_stopcontact
        - switch.roos_stopcontact
    - service: notify.mobile_app_proteus
      data:
        title: "Turned on lights for girls"
        message: "Girls incoming"
