homeassistant:
  customize: !include customize.yml
  time_zone: Europe/Brussels
  unit_system: metric
  elevation: !secret home_elevation
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  name: !secret home_name
  country: BE

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
scene: !include scenes.yaml
script: !include scripts.yaml

# https://www.home-assistant.io/docs/automation/yaml/
automation badkamer: !include automations/badkamer.yaml
automation rest: !include automations/rest.yaml
automation girls: !include automations/wake-girls.yaml
automation location: !include automations/location.yaml

# Integrations
input_datetime: !include integrations/input_datetime.yaml
input_boolean: !include integrations/input_boolean.yaml
timer: !include integrations/timer.yaml
light: !include integrations/light.yaml
homekit: !include integrations/homekit.yaml

# Still in UI: Deconz, Tado, Ubiquiti, Synology, Harmony Hub
logger:
  default: info
  logs:
    pydeconz: debug
    homeassistant.components.deconz: debug
climate:
  - platform: climate_group
    name: 'Climate Ground Floor'
    temperature_unit: C  # default to celsius, 'C' or 'F'
    entities:
    - climate.living
    - climate.keuken
    - climate.goei_kamer

cover: !include cover.yaml
# Legacy: https://www.home-assistant.io/integrations/template#configuration-variables
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
lovelace:
  # Keep the main dashboard, autogenerated using the UI
  mode: storage
  resources:
    - url: /hacsfiles/simple-thermostat/simple-thermostat.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
  dashboards:
    lovelace-yaml:
      mode: yaml
      title: Dashboard
      icon: mdi:truck-fast-outline
      show_in_sidebar: true
      filename: ui/dashboard.yaml
    lovelace-config:
      mode: yaml
      title: Configuration
      icon: mdi:cog
      show_in_sidebar: true
      filename: ui/config.yaml
    lovelace-hothothot:
      mode: yaml
      title: Some like it hot
      icon: mdi:hot-tub
      show_in_sidebar: true
      filename: ui/hothothot.yaml

shell_command:
  send_location: >
    curl -X POST -d "data={{ state_attr("device_tracker.oranje", "latitude") }};{{ state_attr("device_tracker.oranje", "longitude") }};{{ state_attr("device_tracker.oranje", "altitude") }};{{ state_attr("device_tracker.oranje", "battery_level") }}" http://pjmini.local:4567/api/track
