homeassistant:
  customize: !include customize.yml
  time_zone: Europe/Brussels
  unit_system: metric
  elevation: !secret home_elevation
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  name: !secret home_name

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

# Discovery addon https://www.home-assistant.io/integrations/discovery/
discovery:

group: !include groups.yaml
automation: !include automations.yaml
scene: !include scenes.yaml
script: !include scripts.yaml

# Integrations
input_datetime: !include integrations/input_datetime.yaml
input_boolean: !include integrations/input_boolean.yaml
timer: !include integrations/timer.yaml
light: !include integrations/light.yaml
webostv: !include integrations/webostv.yaml
homekit:
  filter:
    include_entities:
      - light.badkamer_hal
      - light.badkamer
      - light.stalamp
      - light.radiolamp
      - light.kleine_rode_lamp
      - light.bureau
      - light.grote_kast_lamp
      - light.hal_voordeur
      - light.buitenlamp
      - switch.fran_stopcontact
      - switch.roos_stopcontact
      - switch.kelder_stopcontact
      - switch.kerstboom
      - climate.bureau

# Still in UI: Deconz, Tado, Ubiquiti, Synology, Harmony Hub
logger:
  default: info
  logs:
    pydeconz: debug
    homeassistant.components.deconz: debug

sensor: !include sensors.yaml
lovelace:
  # Keep the main dashboard, autogenerated using the UI
  mode: storage
  dashboards:
    lovelace-yaml:
      mode: yaml
      title: Dashboard
      icon: mdi:truck-fast-outline
      show_in_sidebar: true
      filename: ui/dashboard.yaml
