homeassistant:
  customize: !include customize.yml
  time_zone: Europe/Brussels
  unit_system: metric
  elevation: !secret home_elevation
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  name: !secret home_name

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

# Discovery addon https://www.home-assistant.io/integrations/discovery/
discovery:

group: !include groups.yaml
automation: !include automations.yaml
scene: !include scenes.yaml
script: !include scripts.yaml

# Integrations
input_datetime: !include integrations/input_datetime.yaml
input_boolean: !include integrations/input_boolean.yaml
timer: !include integrations/timer.yaml
light: !include integrations/light.yaml
webostv: !include integrations/webostv.yaml
homekit: !include integrations/homekit.yaml

# Still in UI: Deconz, Tado, Ubiquiti, Synology, Harmony Hub
logger:
  default: info
  logs:
    pydeconz: debug
    homeassistant.components.deconz: debug

sensor: !include sensors.yaml
lovelace:
  # Keep the main dashboard, autogenerated using the UI
  mode: storage
  resources:
    - url: /hacsfiles/simple-thermostat/simple-thermostat.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
  dashboards:
    lovelace-yaml:
      mode: yaml
      title: Dashboard
      icon: mdi:truck-fast-outline
      show_in_sidebar: true
      filename: ui/dashboard.yaml
    lovelace-config:
      mode: yaml
      title: Configuration
      icon: mdi:cog
      show_in_sidebar: true
      filename: ui/config.yaml
    such-hothothot:
      mode: yaml
      title: ABCD
      icon: mdi:hot-tub
      show_in_sidebar: true
      filename: ui/hothothot.yaml
