- platform: buienradar
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  timeframe: 30
  monitored_conditions:
    - symbol
    - humidity
    - temperature
    - windspeed
    - pressure
    - precipitation_forecast_average
    - rainchance_1d

- platform: template
  sensors:
    office_temperature_offset:
      friendly_name: "Diff on office temp"
      unit_of_measurement: "°C"
      value_template: "{{states('sensor.bureau_temperature')|float - states('sensor.office_sensor_temp')|float}}"

- platform: afvalbeheer
  wastecollector: RecycleApp
  resources:
    - restafval
    - papier
    - pmd
  postcode: !secret home_postal_code
  streetnumber: !secret home_house_number
  streetname: !secret home_streetname
  upcomingsensor: 0
  dateformat: '%d-%m-%Y'
  dateonly: 0
  dateobject: 0
  name: ''
  nameprefix: 1
  builtinicons: 0
  disableicons: 0
  dutch: 0
