- id: on-location-change
  alias: Send location
  description: ''
  trigger:
    - platform: state
      entity_id:
        - device_tracker.oranje
      attribute: latitude
  action:
    service: shell_command.send_location

- alias: "loc. Arm the outside"
  id: arm-the-outside
  mode: single
  trigger:
    - platform: numeric_state
      entity_id: sensor.home_piet_distance
      above: 200
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.pj_outside_zone

- alias: "loc. Notify about being away"
  id: notify-arm
  mode: single
  triggers:
    - trigger: state
      entity_id: person.piet_jaspers
      to: "away"
  actions:
    - action:  notify.mobile_app_oranje
      data:
        message: pjaspers has left the building

- alias: "loc. pj arrived home"
  id: pj-arrived-home
  mode: single
  trigger:
    - trigger: state
      entity_id: person.piet_jaspers
      from: away
      to: home
  action:
    - event: "x-pj-returned-home"

- alias: "loc. ch arrived home"
  id: ch-arrived-home
  mode: single
  trigger:
    - trigger: state
      entity_id: person.christine
      from: away
      to: home
  action:
    - event: "x-ch-returned-home"

- id: "pj-returned-home"
  alias: "Piet returning home"
  triggers:
    - trigger: event
      event_type: x-pj-returned-home
  conditions:
    - condition: state
      entity_id: input_boolean.pj_automatic_garage_opener
      state: "on"
  actions:
    - service: notify.mobile_app_oranje
      data:
        title: You returned home!
        message: Opening the pod bay doors (because you asked me)
    - action:  input_boolean.turn_off
      data:
        entity_id: input_boolean.pj_automatic_garage_opener
    - action:  cover.open_cover
      data:
        entity_id: cover.garage_door

- id: "ch-returned-home"
  alias: "Christine returning home"
  triggers:
    - trigger: event
      event_type: x-ch-returned-home
  conditions:
    - condition: state
      entity_id: input_boolean.ch_automatic_garage_opener
      state: "on"
  actions:
    - service: notify.mobile_app_stienfoon
      data:
        title: Je bent thuis!
        message: Ik open de garage (omdat je dat wou)
    - action:  input_boolean.turn_off
      data:
        entity_id: input_boolean.ch_automatic_garage_opener
    - action:  cover.open_cover
      data:
        entity_id: cover.garage_door
