- id: on-location-change
  alias: Send location
  description: ''
  trigger:
    - platform: state
      entity_id:
        - device_tracker.oranje
      attribute: latitude
  action:
    service: shell_command.send_location

- alias: "loc. Arm the outside"
  id: arm-the-outside
  mode: single
  trigger:
    - platform: numeric_state
      entity_id: sensor.home_piet_distance
      above: 200
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.pj_outside_zone

- alias: "loc. Notify about arming"
  id: notify-arm
  mode: single
  triggers:
    - trigger: state
      entity_id: input_boolean.pj_outside_zone
      to: "on"
  actions:
    - action:  notify.mobile_app_oranje
      data:
        message: pjaspers has left the building

- alias: "loc. Arrived home"
  id: arrived-home
  mode: single
  condition:
    - condition: state
      entity_id: input_boolean.pj_outside_zone
      state: "on"
  trigger:
    - platform: state
      entity_id: person.piet_jaspers
      to: home
  action:
    - service: notify.mobile_app_oranje
      data:
        title: You returned home!
        message: Salutations!
    - event: "x-returned-home"
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.pj_outside_zone

# Christine bericht sturen en mij bericht sturen
- id: "x-returned-home"
  alias: "Returning home"
  triggers:
    - trigger: event
      event_type: x-returned-home
  conditions:
    - condition: state
      entity_id: input_boolean.arm_the_automatic_garage_opener
      state: "on"
  actions:
    - action:  input_boolean.turn_off
      data:
        entity_id: input_boolean.arm_the_automatic_garage_opener
    - action:  cover.open_cover
      data:
        entity_id: cover.garage_door
