- id: on-location-change
  alias: Send location
  description: ''
  trigger:
    - platform: state
      entity_id:
        - device_tracker.oranje
      attribute: latitude
  action:
    service: shell_command.send_location

- alias: "loc. Arm the outside"
  id: arm-the-outside
  mode: single
  trigger:
    - platform: numeric_state
      entity_id: sensor.home_piet_distance
      above: 200
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.pj_outside_zone

- alias: "loc. Returning home"
  id: returning-home
  mode: single
  condition:
    - condition: state
      entity_id: input_boolean.pj_outside_zone
      state: "on"
  trigger:
    - platform: numeric_state
      entity_id: sensor.home_piet_distance
      below: 100
  action:
    - service: notify.mobile_app_oranje
      data:
        title: You have returned within 100m
        message: Greetings!

- alias: "loc. Arrived home"
  id: arrived-home
  mode: single
  condition:
    - condition: state
      entity_id: input_boolean.pj_outside_zone
      state: "on"
  trigger:
    - platform: state
      entity_id: person.piet_jaspers
      to: home
  action:
    - service: notify.mobile_app_oranje
      data:
        title: You are in the zone
        message: Salutations!

- alias: "loc. Also home"
  id: also-home
  mode: single
  condition:
    - condition: state
      entity_id: input_boolean.pj_outside_zone
      state: "on"
  trigger:
    - platform: numeric_state
      entity_id: sensor.home_piet_distance
      below: 2
  action:
    - service: notify.mobile_app_oranje
      data:
        title: You are at your doorstep
        message: Salutations!
