- id: nighty-night
  alias: Turn off the lights at night
  description: ''
  trigger:
  - at: input_datetime.go_to_bed_house
    platform: time
  condition: []
  action:
  - service: scene.turn_on
    data:
      entity_id: scene.night
      transition: 10
- id: evening-mode
  alias: Turn on lights an hour before sunset
  description: ''
  trigger:
  - event: sunset
    offset: -01:00:00
    platform: sun
  condition: []
  action:
  - service: scene.turn_on
    data:
      entity_id: scene.sunset
      transition: 10
  mode: single
- id: day-mode
  alias: Turn off lights at 9
  description: No need for lights during the day
  trigger:
  - platform: time
    at: 09:00
  condition: []
  action:
  - service: script.turn_on
    entity_id: script.turn_off_downstairs
  - service: light.turn_off
    entity_id: light.badkamer_hal
- id: light-submarine
  alias: Make the hallway use red light at night
  trigger:
  - platform: time
    at: input_datetime.submarine_house
  action:
  - service: light.turn_on
    entity_id: light.badkamer_hal
    data:
      brightness: 50
      color_name: red
- id: presence-leave
  alias: Turn off things when leaving
  trigger:
  - platform: state
    entity_id: person.piet_jaspers
    to: not_home
  action:
  - service: notify.mobile_app_proteus
    data:
      title: You not here
      message: You left
- id: morning-mode
  alias: Make waking up less of a hassle
  trigger:
  - platform: time
    at: input_datetime.wake_up_house
  action:
  - service: scene.turn_on
    data:
      entity_id: scene.morning
      transition: 10
- id: '1606908289501'
  alias: Turn on basement light when there is movement
  trigger:
    - platform: state
      entity_id: binary_sensor.presence_2
      from: 'off'
      to: 'on'
  action:
  - service: homeassistant.turn_on
    data:
      entity_id: switch.kelder_stopcontact
- id: '1606908325908'
  alias: Turn off basement light 10 minutes after last movement
  trigger:
  - platform: state
    entity_id: binary_sensor.presence_2
    from: "on"
    to: "off"
    for:
      minutes: 5
  action:
  - service: homeassistant.turn_off
    data:
      entity_id: switch.kelder_stopcontact
- id: '1607795493492'
  alias: Kattenbak
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 346efe062200efe1b1ba6082021c0148
    entity_id: binary_sensor.tradfri_motion_sensor
    domain: binary_sensor
  condition: []
  action:
  - service: notify.living_room_tv
    data:
      message: Kattenbak beweging
  mode: single

- alias: Background light on when camera on
  trigger:
    platform: state
    entity_id: binary_sensor.pj_mini_camera_in_use
    from: "off"
    to: "on"
    for: 0:00:02
  action:
    service: homeassistant.turn_on
    entity_id: light.bureau

- alias: Background light off when camera off
  trigger:
    platform: state
    entity_id: binary_sensor.pj_mini_camera_in_use
    from: "on"
    to: "off"
    for: 0:00:02
  action:
    service: homeassistant.turn_off
    entity_id: light.bureau
