title: Configuration
views:
  - path: config
    cards:
      - type: entities
        entities:
          - input_datetime.go_to_bed_house
          - input_datetime.submarine_house
          - input_datetime.wake_up_house
          - input_datetime.alarm_clock_girls
          - input_datetime.alarm_clock_girls_weekend
          - input_boolean.ch_automatic_garage_opener
          - input_boolean.pj_automatic_garage_opener
